/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve all elemental types
         * @description Fetches the full catalog of registered Pokémon elemental types.
         */
        get: operations["getTypes"];
        put?: never;
        /**
         * Create a new elemental type
         * @description Registers a unique elemental type (e.g. Electric, Water, Fire) in the system.
         */
        post: operations["createType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve all combat stats
         * @description Fetches the full catalog of registered Pokémon combat statistics (e.g. HP, Attack, Defense, Speed).
         */
        get: operations["getStats"];
        put?: never;
        /**
         * Create a new combat stat
         * @description Registers a unique base combat statistic (e.g. Special Attack, Defense) in the Pokédex system.
         */
        post: operations["createStat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pokemons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve all Pokémon
         * @description Fetches a complete list of all registered Pokémon along with their types, stats, and evolutions.
         */
        get: operations["getAllPokemon"];
        put?: never;
        /**
         * Create a new Pokémon
         * @description Registers a new Pokémon with physical dimensions, theme color, assigned types, and initial stats.
         */
        post: operations["createPokemon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete elemental type
         * @description Deletes an elemental type from the system by its unique identifier.
         */
        delete: operations["deleteType"];
        options?: never;
        head?: never;
        /**
         * Update elemental type
         * @description Updates the name of an existing elemental type by its unique identifier.
         */
        patch: operations["updateType"];
        trace?: never;
    };
    "/stats/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete combat stat
         * @description Deletes a combat statistic from the system by its unique identifier.
         */
        delete: operations["deleteStat"];
        options?: never;
        head?: never;
        /**
         * Update combat stat
         * @description Updates the name of an existing combat statistic by its unique identifier.
         */
        patch: operations["updateStat"];
        trace?: never;
    };
    "/pokemons/{pokemonId}/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Assign elemental types to Pokémon
         * @description Replaces the elemental types assigned to the specified Pokémon (1 or 2 types allowed).
         */
        patch: operations["assignPokemonTypes"];
        trace?: never;
    };
    "/pokemons/{pokemonId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Assign stats to Pokémon
         * @description Replaces or updates combat stat assignments for the specified Pokémon.
         */
        patch: operations["assignPokemonStats"];
        trace?: never;
    };
    "/pokemons/{pokemonId}/evolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Assign evolutions to Pokémon
         * @description Configures forward evolution paths and target Pokémon IDs for the specified Pokémon.
         */
        patch: operations["assignEvolutions"];
        trace?: never;
    };
    "/pokemons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pokémon by ID
         * @description Retrieves a single Pokémon profile by its unique integer identifier.
         */
        get: operations["getById"];
        put?: never;
        post?: never;
        /**
         * Delete Pokémon
         * @description Removes a Pokémon and its associated stats, types, and evolution relationships from the Pokédex.
         */
        delete: operations["deletePokemon"];
        options?: never;
        head?: never;
        /**
         * Update Pokémon details
         * @description Partially updates general information (name, description, avatar, height, weight, color) of an existing Pokémon.
         */
        patch: operations["updatePokemon"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Payload required to create a new elemental Pokémon type. */
        CreateTypeRequest: {
            /**
             * @description Unique name of the elemental type.
             * @example Electric
             */
            name: string;
        };
        /** @description Elemental type name representation. */
        TypeName: {
            /**
             * @description Elemental type name.
             * @example grass
             */
            value?: string;
        };
        /** @description Global Pokémon elemental type definition. */
        TypeResponse: {
            /**
             * Format: int32
             * @description Unique numeric identifier of the elemental type.
             * @example 1
             */
            id?: number;
            /** @description Elemental type name object. */
            name?: components["schemas"]["TypeName"];
        };
        /** @description Standardized error response payload following RFC 7807 problem details structure. */
        ErrorResponse: {
            /**
             * Format: date-time
             * @description UTC timestamp when the error occurred.
             * @example 2026-08-25T10:00:00Z
             */
            timestamp?: string;
            /**
             * Format: int32
             * @description HTTP status code.
             * @example 400
             */
            status?: number;
            /**
             * @description HTTP status reason phrase.
             * @example Bad Request
             */
            error?: string;
            /**
             * @description Human-readable description of the error.
             * @example The request contains validation errors
             */
            message?: string;
            /** @description Collection of field-level validation errors, if applicable. */
            errors?: components["schemas"]["FieldError"][];
        };
        /** @description Details about a specific field-level validation failure. */
        FieldError: {
            /**
             * @description Name of the invalid property/field.
             * @example name
             */
            field?: string;
            /**
             * @description The rejected invalid value supplied by the client.
             * @example P
             */
            value?: unknown;
            /**
             * @description Validation failure reason message.
             * @example Name must be between 2 and 50 characters
             */
            message?: string;
        };
        /** @description Payload required to register a new base combat statistic. */
        CreateStatRequest: {
            /**
             * @description Name of the combat statistic.
             * @example Speed
             */
            name: string;
        };
        /** @description Combat statistic name representation. */
        StatName: {
            /**
             * @description Combat statistic name.
             * @example speed
             */
            value?: string;
        };
        /** @description Global Pokémon base combat statistic definition. */
        StatResponse: {
            /**
             * Format: int32
             * @description Unique numeric identifier of the combat statistic.
             * @example 1
             */
            id?: number;
            /** @description Combat statistic name object. */
            name?: components["schemas"]["StatName"];
        };
        /** @description Payload required to register a new Pokémon profile. */
        CreatePokemonRequest: {
            /**
             * @description Name of the Pokémon.
             * @example Pikachu
             */
            name: string;
            /**
             * @description Detailed lore and Pokédex entry description.
             * @example When it smashes its foes with its tail, it releases strong electric shocks.
             */
            description: string;
            /**
             * @description URL pointing to the Pokémon official artwork or sprite.
             * @example https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png
             */
            avatar: string;
            /**
             * Format: double
             * @description Height of the Pokémon in meters.
             * @example 0.4
             */
            height: number;
            /**
             * Format: double
             * @description Weight of the Pokémon in kilograms.
             * @example 6
             */
            weight: number;
            /** @description Color configuration (RGB) for Pokémon theme. */
            color: components["schemas"]["PokemonColorRequest"];
            /** @description Set of elemental Type IDs (between 1 and 2 types allowed). */
            typeIds: number[];
            /** @description Set of initial combat stat assignments. */
            stats: components["schemas"]["PokemonStatRequest"][];
        };
        /** @description RGB color definition for the Pokémon UI card theme. */
        PokemonColorRequest: {
            /**
             * Format: int32
             * @description Red channel intensity (0-255).
             * @example 255
             */
            r: number;
            /**
             * Format: int32
             * @description Green channel intensity (0-255).
             * @example 204
             */
            g: number;
            /**
             * Format: int32
             * @description Blue channel intensity (0-255).
             * @example 0
             */
            b: number;
        };
        /** @description Stat identifier and value assigned to a Pokémon. */
        PokemonStatRequest: {
            /**
             * Format: int32
             * @description Identifier of the base combat stat.
             * @example 1
             */
            statId: number;
            /**
             * Format: int32
             * @description Base stat value for this Pokémon (1-255).
             * @example 35
             */
            value: number;
        };
        /** @description RGB color profile used for UI theming. */
        PokemonColor: {
            /**
             * Format: int32
             * @description Red channel intensity (0-255).
             * @example 246
             */
            red?: number;
            /**
             * Format: int32
             * @description Green channel intensity (0-255).
             * @example 211
             */
            green?: number;
            /**
             * Format: int32
             * @description Blue channel intensity (0-255).
             * @example 5
             */
            blue?: number;
        };
        /** @description Evolution relationship target and progression sequence. */
        PokemonEvolution: {
            /**
             * Format: int32
             * @description Identifier of the target evolved Pokémon.
             * @example 26
             */
            toPokemonId?: number;
            /**
             * Format: int32
             * @description Progression order/stage in the evolution chain.
             * @example 1
             */
            order?: number;
        };
        /** @description Detailed profile and catalog information of a Pokémon. */
        PokemonResponse: {
            /**
             * Format: int32
             * @description Unique numeric identifier of the Pokémon.
             * @example 25
             */
            id?: number;
            /**
             * @description Name of the Pokémon.
             * @example pikachu
             */
            name?: string;
            /**
             * @description Official lore and Pokédex entry description.
             * @example When several of these Pokémon gather, their electricity could build and cause lightning storms.
             */
            description?: string;
            /**
             * @description URL pointing to the official artwork or sprite.
             * @example https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/25.png
             */
            avatar?: string;
            /**
             * Format: double
             * @description Height of the Pokémon in meters.
             * @example 0.4
             */
            height?: number;
            /**
             * Format: double
             * @description Weight of the Pokémon in kilograms.
             * @example 6
             */
            weight?: number;
            /** @description RGB color profile used for UI theming. */
            color?: components["schemas"]["PokemonColor"];
            /** @description Set of assigned elemental type IDs. */
            types?: number[];
            /** @description Set of base combat statistics assigned to this Pokémon. */
            stats?: components["schemas"]["PokemonStat"][];
            /** @description Set of forward evolution transitions available for this Pokémon. */
            evolutions?: components["schemas"]["PokemonEvolution"][];
        };
        /** @description Assigned base combat statistic value. */
        PokemonStat: {
            /**
             * Format: int32
             * @description Identifier of the combat statistic.
             * @example 1
             */
            statId?: number;
            /**
             * Format: int32
             * @description Base stat value for this Pokémon (1-255).
             * @example 35
             */
            value?: number;
        };
        /** @description Payload required to update an existing elemental Pokémon type name. */
        UpdateTypeRequest: {
            /**
             * @description Updated unique name of the elemental type.
             * @example Fire
             */
            name: string;
        };
        /** @description Payload required to update an existing combat statistic name. */
        UpdateStatRequest: {
            /**
             * @description Updated name of the combat statistic.
             * @example Attack
             */
            name: string;
        };
        /** @description Set of type IDs to assign to the Pokémon (replaces previous type assignments). */
        AssignPokemonTypesRequest: {
            /** @description Set of elemental Type IDs (1 to 2 allowed). */
            typeIds: number[];
        };
        /** @description Set of combat stats to assign to the Pokémon (replaces previous stat values). */
        AssignPokemonStatsRequest: {
            /** @description Set of stat ID and value mappings. */
            stats: components["schemas"]["PokemonStatRequest"][];
        };
        /** @description Set of evolution transitions to assign to the Pokémon. */
        AssignPokemonEvolutionsRequest: {
            /** @description Set of target evolutions with their order. */
            evolutions: components["schemas"]["PokemonEvolutionRequest"][];
        };
        /** @description Target Pokémon identifier and sequence order in the evolution line. */
        PokemonEvolutionRequest: {
            /**
             * Format: int32
             * @description Identifier of the target evolved Pokémon.
             * @example 26
             */
            toPokemonId: number;
            /**
             * Format: int32
             * @description Progression order/stage in the evolution chain.
             * @example 1
             */
            order: number;
        };
        /** @description Payload required to partially update Pokémon details. All fields are optional. */
        UpdatePokemonRequest: {
            /**
             * @description Updated name of the Pokémon.
             * @example Raichu
             */
            name?: string;
            /**
             * @description Updated Pokédex entry description.
             * @example Its long tail serves as a ground to protect itself from its own high-voltage power.
             */
            description?: string;
            /**
             * @description Updated URL for the official artwork/sprite.
             * @example https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png
             */
            avatar?: string;
            /**
             * Format: double
             * @description Updated height of the Pokémon in meters.
             * @example 0.8
             */
            height?: number;
            /**
             * Format: double
             * @description Updated weight of the Pokémon in kilograms.
             * @example 30
             */
            weight?: number;
            /** @description Updated RGB color profile. */
            color?: components["schemas"]["PokemonColorRequest"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type CreateTypeRequest = components['schemas']['CreateTypeRequest'];
export type TypeName = components['schemas']['TypeName'];
export type TypeResponse = components['schemas']['TypeResponse'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type FieldError = components['schemas']['FieldError'];
export type CreateStatRequest = components['schemas']['CreateStatRequest'];
export type StatName = components['schemas']['StatName'];
export type StatResponse = components['schemas']['StatResponse'];
export type CreatePokemonRequest = components['schemas']['CreatePokemonRequest'];
export type PokemonColorRequest = components['schemas']['PokemonColorRequest'];
export type PokemonStatRequest = components['schemas']['PokemonStatRequest'];
export type PokemonColor = components['schemas']['PokemonColor'];
export type PokemonEvolution = components['schemas']['PokemonEvolution'];
export type PokemonResponse = components['schemas']['PokemonResponse'];
export type PokemonStat = components['schemas']['PokemonStat'];
export type UpdateTypeRequest = components['schemas']['UpdateTypeRequest'];
export type UpdateStatRequest = components['schemas']['UpdateStatRequest'];
export type AssignPokemonTypesRequest = components['schemas']['AssignPokemonTypesRequest'];
export type AssignPokemonStatsRequest = components['schemas']['AssignPokemonStatsRequest'];
export type AssignPokemonEvolutionsRequest = components['schemas']['AssignPokemonEvolutionsRequest'];
export type PokemonEvolutionRequest = components['schemas']['PokemonEvolutionRequest'];
export type UpdatePokemonRequest = components['schemas']['UpdatePokemonRequest'];
export type $defs = Record<string, never>;
export interface operations {
    getTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of elemental types retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeResponse"][];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTypeRequest"];
            };
        };
        responses: {
            /** @description Elemental type created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeResponse"];
                };
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the resource (e.g. unique constraint violation). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of combat stats retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatResponse"][];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createStat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStatRequest"];
            };
        };
        responses: {
            /** @description Combat stat created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatResponse"];
                };
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the resource (e.g. unique constraint violation). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAllPokemon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Pokémon retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokemonResponse"][];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createPokemon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePokemonRequest"];
            };
        };
        responses: {
            /** @description Pokémon created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokemonResponse"];
                };
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the resource (e.g. unique constraint violation). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique numeric identifier of the elemental type to delete
                 * @example 13
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Elemental type deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique numeric identifier of the elemental type
                 * @example 13
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTypeRequest"];
            };
        };
        responses: {
            /** @description Elemental type updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeResponse"];
                };
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the resource (e.g. unique constraint violation). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteStat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique numeric identifier of the combat statistic to delete
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combat stat deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateStat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique numeric identifier of the combat statistic
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStatRequest"];
            };
        };
        responses: {
            /** @description Combat stat updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatResponse"];
                };
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the resource (e.g. unique constraint violation). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    assignPokemonTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique numeric identifier of the Pokémon
                 * @example 25
                 */
                pokemonId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPokemonTypesRequest"];
            };
        };
        responses: {
            /** @description Types assigned successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    assignPokemonStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique numeric identifier of the Pokémon
                 * @example 25
                 */
                pokemonId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPokemonStatsRequest"];
            };
        };
        responses: {
            /** @description Stats assigned successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    assignEvolutions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique numeric identifier of the base Pokémon
                 * @example 25
                 */
                pokemonId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPokemonEvolutionsRequest"];
            };
        };
        responses: {
            /** @description Evolutions assigned successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the resource (e.g. unique constraint violation). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique numeric identifier of the Pokémon
                 * @example 25
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pokémon found and retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokemonResponse"];
                };
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deletePokemon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique numeric identifier of the Pokémon to delete
                 * @example 25
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pokémon deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updatePokemon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique numeric identifier of the Pokémon to update
                 * @example 25
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePokemonRequest"];
            };
        };
        responses: {
            /** @description Pokémon updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokemonResponse"];
                };
            };
            /** @description The request is invalid, contains malformed JSON, or fails field-level validation constraints. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the resource (e.g. unique constraint violation). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal server error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
