import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.resolve(__dirname, '..');
const TOKENS_PATH = path.join(ROOT_DIR, 'src', 'tokens.json');
const ICONS_DIR = path.join(ROOT_DIR, 'assets', 'icons');
const GEN_WEB_DIR = path.join(ROOT_DIR, 'generated', 'web');
const GEN_FLUTTER_DIR = path.join(ROOT_DIR, 'generated', 'flutter');

// Crear carpetas de salida
fs.mkdirSync(GEN_WEB_DIR, { recursive: true });
fs.mkdirSync(GEN_FLUTTER_DIR, { recursive: true });

const tokens = JSON.parse(fs.readFileSync(TOKENS_PATH, 'utf-8'));

// Helper: Convertir hex a formato Flutter Color(0xFF...) o Color(0x...) si tiene alpha
function hexToFlutterColor(hex: string): string {
  const cleanHex = hex.replace('#', '');
  if (cleanHex.length === 8) {
    // #RRGGBBAA -> Color(0xAARRGGBB) en Flutter
    const rr = cleanHex.slice(0, 2);
    const gg = cleanHex.slice(2, 4);
    const bb = cleanHex.slice(4, 6);
    const aa = cleanHex.slice(6, 8);
    return `Color(0x${aa.toUpperCase()}${rr.toUpperCase()}${gg.toUpperCase()}${bb.toUpperCase()})`;
  }
  return `Color(0xFF${cleanHex.toUpperCase()})`;
}

// Helper: Convertir a camelCase y PascalCase
function toCamelCase(str: string): string {
  return str.replace(/[-_]([a-z0-9])/gi, (_, char) => char.toUpperCase());
}

function toPascalCase(str: string): string {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

// 1. GENERAR WEB: tokens.css
let cssContent = `/* Auto-generated by @pokedex/ui. Do not edit directly. */\n:root {\n`;
for (const [category, values] of Object.entries(tokens.color as Record<string, Record<string, string>>)) {
  for (const [key, val] of Object.entries(values)) {
    cssContent += `  --pk-color-${category}-${key}: ${val};\n`;
  }
}
cssContent += `}\n`;
fs.writeFileSync(path.join(GEN_WEB_DIR, 'tokens.css'), cssContent);

// 2. GENERAR WEB: tokens.ts
const tsContent = `// Auto-generated by @pokedex/ui. Do not edit directly.
export const POKEDEX_TOKENS = ${JSON.stringify(tokens, null, 2)} as const;

export type PokedexTokens = typeof POKEDEX_TOKENS;
export type PokemonBackground = keyof typeof POKEDEX_TOKENS.color.background;
export type PokemonText = keyof typeof POKEDEX_TOKENS.color.text;
export type PokemonBorder = keyof typeof POKEDEX_TOKENS.color.border;
export type PokemonStat = keyof typeof POKEDEX_TOKENS.color.stats;
export type PokemonType = keyof typeof POKEDEX_TOKENS.color.types;
`;
fs.writeFileSync(path.join(GEN_WEB_DIR, 'tokens.ts'), tsContent);

// 3. GENERAR WEB: icons.ts
const iconFiles = fs.existsSync(ICONS_DIR)
  ? fs.readdirSync(ICONS_DIR).filter((file: string) => file.endsWith('.svg'))
  : [];
const iconsMap: Record<string, string> = {};

for (const file of iconFiles) {
  const iconName = path.basename(file, '.svg');
  const svgContent = fs.readFileSync(path.join(ICONS_DIR, file), 'utf-8').trim();
  iconsMap[iconName] = svgContent;
}

const iconsTsContent = `// Auto-generated by @pokedex/ui. Do not edit directly.
export const POKEDEX_ICONS = ${JSON.stringify(iconsMap, null, 2)} as const;
export type PokedexIconName = keyof typeof POKEDEX_ICONS;
`;
fs.writeFileSync(path.join(GEN_WEB_DIR, 'icons.ts'), iconsTsContent);

// 4. GENERAR FLUTTER: pokedex_tokens.dart
let dartContent = `// Auto-generated by @pokedex/ui. Do not edit directly.
import 'package:flutter/material.dart';

abstract class PokedexTokens {
  // --- Background Colors ---
`;
for (const [key, val] of Object.entries(tokens.color.background as Record<string, string>)) {
  dartContent += `  static const Color bg${toPascalCase(key)} = ${hexToFlutterColor(val)};\n`;
}

dartContent += `\n  // --- Text Colors ---\n`;
for (const [key, val] of Object.entries(tokens.color.text as Record<string, string>)) {
  dartContent += `  static const Color text${toPascalCase(key)} = ${hexToFlutterColor(val)};\n`;
}

dartContent += `\n  // --- Border Colors ---\n`;
for (const [key, val] of Object.entries(tokens.color.border as Record<string, string>)) {
  dartContent += `  static const Color border${toPascalCase(key)} = ${hexToFlutterColor(val)};\n`;
}

dartContent += `\n  // --- Stats Colors ---\n`;
for (const [key, val] of Object.entries(tokens.color.stats as Record<string, string>)) {
  dartContent += `  static const Color stat${toPascalCase(key)} = ${hexToFlutterColor(val)};\n`;
}

dartContent += `\n  // --- Types Colors ---\n`;
for (const [key, val] of Object.entries(tokens.color.types as Record<string, string>)) {
  dartContent += `  static const Color type${toPascalCase(key)} = ${hexToFlutterColor(val)};\n`;
}

dartContent += `}\n`;
fs.writeFileSync(path.join(GEN_FLUTTER_DIR, 'pokedex_tokens.dart'), dartContent);

console.log('✅ Tokens e Iconos compilados exitosamente para Web y Flutter.');


