spring.application.name=pokedex

# define el prefijo global para toda la API REST
server.servlet.context-path=/api/v1

# configuracion de conexion PostgreSQL
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=user
spring.datasource.password=password

# crear tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Swagger
## Ruta personalizada para acceder a la UI de Swagger
springdoc.swagger-ui.path=/api-docs/swagger-ui.html
## Ordenar los endpoints en la interfaz por su metodo HTTP (GET, POST, etc.)
springdoc.swagger-ui.operationsSorter=method
## Titulo y version general de la API
springdoc.api-docs.path=/api-docs
application.version=1.0.0
application.name=Pokedex API